version: '3.8'
services:
  db:
    container_name: db
    hostname: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=web_project_db
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    expose:
      - 5432
  app:
    container_name: app-sm
    image: luisgamez/unimag-store-backend:v1
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    #command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    command: /app/startup.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - SQL_ALCHEMY_DATABASE_URI=postgresql://root:root@db/web_project_db
    depends_on:
      - db